import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSession, signOut, signIn } from "next-auth/react";
import { Page } from "@/components/layouts/Page";
import { PageContent } from "@/components/layouts/PageContent";
import { Container } from "@/components/layouts/Container";
import { useEffect, useState } from "react";
import Link from "next/link";
import useSWR from "swr";
import { JalaLogo, LoadingLogo } from "@/components/icons/JalaLogo";
import { fetcher } from "@/utils/fetcher";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setValue] = useState("https://syauqy.dev");
  const [links, setLinks] = useState({});

  const { data: session, status } = useSession();

  useEffect(() => {
    if (!session && status == "unauthenticated") {
      signIn();
    }
  }, [session]);

  console.log(session);

  const handleInputChange = (event: any) => {
    console.log(event);
    setValue(event.target.value);
    // const { name, value } = event.target;
    // setProfileData((prevSettings) => ({
    //   ...prevSettings,
    //   [name]: value,
    // }));
  };

  const handleSubmit = async (e: any) => {
    e.preventDefault();

    await fetch("/api/shorten", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url: value }),
    });
  };

  const getLinks = async () => {
    // const response = await fetch("/api/links", {
    //   method: "GET",
    // }).then((res) => {
    //   // console.log(res);
    //   return res.json();
    // });
    // return response;
    const url = await fetch(
      `${process.env.NEXT_PUBLIC_AIRTABLE_URI}/links?filterByFormula=shortname='abcde'`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${process.env.NEXT_PUBLIC_AIRTABLE_TOKEN}`,
        },
      }
    ).then((res) => {
      return res.json();
    });
    return url;
  };

  const refreshLinks = async () => {
    console.log("refresh");
    const linksObjects = await getLinks();
    console.log(linksObjects);
    setLinks(linksObjects);
  };

  useEffect(() => {
    // async () => {
    //   await refreshLinks();
    // };
    refreshLinks();
  }, []);

  console.log(links);
  return (
    <>
      <Head>
        <title>Udan.gg Url Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <PageContent>
          <Container>
            <div className="flex flex-col gap-4 text-slate-700 space-y-2 relative pb-16">
              <form className="form flex flex-row" onSubmit={handleSubmit}>
                <input value={value} onChange={handleInputChange} />
                <button type="submit">Shorten Url!</button>
              </form>
              {/* <div className="">
                {links ? (
                  Object.keys(links).map((link: any, i) => {
                    const long = links[link];
                    return (
                      <div className="flex flex-row" key={i}>
                        <div>
                          <a
                            href={`http://localhost:3000/${link}`}
                          >{`http://localhost:3000/${link}`}</a>
                        </div>
                        <div></div>
                      </div>
                    );
                  })
                ) : (
                  <></>
                )}
              </div> */}
            </div>
          </Container>
        </PageContent>
      </Page>
    </>
  );
}
