import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Page } from "@/components/layouts/Page";
import { PageContent } from "@/components/layouts/PageContent";
import { Container } from "@/components/layouts/Container";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setValue] = useState("https://syauqy.dev");

  const handleInputChange = (event: any) => {
    console.log(event);
    setValue(event.target.value);
    // const { name, value } = event.target;
    // setProfileData((prevSettings) => ({
    //   ...prevSettings,
    //   [name]: value,
    // }));
  };

  const handleSubmit = async (e: any) => {
    e.preventDefault();

    await fetch("/api/shorten", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url: value }),
    });
  };
  return (
    <>
      <Head>
        <title>Udan.gg Url Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <PageContent>
          <Container>
            <div className="flex flex-col gap-4">
              <form className="form flex flex-row" onSubmit={handleSubmit}>
                <input value={value} onChange={handleInputChange} />
                <button type="submit">Shorten Url!</button>
              </form>
            </div>
          </Container>
        </PageContent>
      </Page>
    </>
  );
}
